### ISSUE TITLE
Test with -faddress=sanitize

### ISSUE THREAD

**Issue by springmeyer** [mapbox/dawg-cache#5]
The dawg-cache code makes extensive usage of array access without bounds checking. To ensure we are not vulnerable to undefined behavior we should test, per commit, on travis with `-faddress=sanitize` enable. This will catch potential bugs fast.

**Comment by springmeyer** [comment]
@apendleton I'm planning on working on a branch soon that enables the sanitizers. Will you have a chance soon to land the fixes in https://github.com/mapbox/dawg-cache/tree/fix-sanitizer?

**Comment by apendleton** [comment]
Yep, at a minimum I can get that merged and do a release today (though I'm not sure whether or not I'll get carmen's dep bumped today or not -- need to see what else is moving there).

**Comment by springmeyer** [comment]
Done and running on travis after #22
