### ISSUE TITLE
Remove unused code?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/dawg-cache#9]
@apendleton I noticed that the `CompactLookup` and `Crc32c` functions are untested: https://github.com/mapbox/dawg-cache/blob/b03e2bc7197b706bfe7d3285553c31a3eaeb62cc/src/binding.cpp#L401-L410

Can this code be removed?

**Comment by springmeyer** [comment]
Ah, nvm, missed seeing them in the index.js https://github.com/mapbox/dawg-cache/blob/master/index.js

**Comment by apendleton** [comment]
Ha, yeah, was gonna say: compact lookup is basically the only way carmen uses this library at all, at least at query time.
